# Generated by Django 4.1.7 on 2023-03-04 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='inventroy',
            new_name='inventory',
        ),
    ]
